### ISSUE TITLE
Missing manifest

### ISSUE THREAD

**Issue by randombyte-developer** [djxy/PermissionManager#1]
When starting the sponge vanilla server build 318 with plugin version 1.2 or 1.3(I only tested them):
` [17:36:26 WARN] [Sponge]: Missing JAR manifest in mods/PermissionManager-1.2.jar`

**Comment by djxy** [comment]
Does it works? I haven't tested on Sponge Vanilla.

**Comment by randombyte-developer** [comment]
No. Commands not registered and plugin not listed in /sponge plugins

**Comment by djxy** [comment]
Okay, I will check that, but I never heard about the Jar manifest for Sponge.

**Comment by randombyte-developer** [comment]
In my plugins is automatically a folder META-INF with a file MANIFEST.MF which just contains "Manifest-Version: 1.0".

**Comment by djxy** [comment]
Okay, I will make it generate automatically now. Thank you.
