### ISSUE TITLE
FML has found a non-mod file

### ISSUE THREAD

**Issue by Fujikatoma** [djxy/PermissionManager#10]
"FML has found a non-mod file PermissionManager-1.2.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible."

What does this error mean ? I'm using the newest Forge/Sponge/Plugin version

**Comment by djxy** [comment]
This version of PermissionManager isn't compatible with the newest version of Sponge. It works with Sponge 4.1. I will release soon the new version of PermissionManager.
