### ISSUE TITLE
'Check' command

### ISSUE THREAD

**Issue by MarkL4YG** [djxy/PermissionManager#11]
For debugging purposes I would like to suggest a command for checking certain things like if a player hat got a certain permission.

Could be ``pm check [player|group] <subject> [permission]``
and would return if the permission value is false or true.

For checking if a player is in a specific group (or a group has a specific player as member) it could be:
``pm check [player|group] <subject> [player|group] <searchSubject>``
and would return true or false again.

**Comment by djxy** [comment]
This version of PermissionManager won't be updated anymore. The new version of PermissionManager contains more options to check if a player/group has a permission or a group.

**Comment by MarkL4YG** [comment]
Uhm, stupid question, but: Do you have a link for me ;)

**Comment by djxy** [comment]
The plugin is not released yet but it's finished.(I wait some translations and the wiki not finished)

You can look the wiki. It contains the commands and the permissions.

https://github.com/djxy/PermissionManager-2.0

**Comment by MarkL4YG** [comment]
Thanks
