### ISSUE TITLE
[Feature Request] I need the ability to set a Promotion permission to a specific promotion.

### ISSUE THREAD

**Issue by GazbonicAcid** [djxy/PermissionManager#26]
I am using Permissions Manager because of its rules system and the plugins its rules system supports.
However I need the ability to set a Promotion permission to a specific promotion.
I need it so that I can have On-Duty and Off-Duty modes for various staff ranks.
I'm using Promotions to facilitate that, however I need to restrict the various staff ranks to only be able to use their own off-duty and on-duty promotions.
PermissionsEx has this kind of specificity for it's equivalent commands in their ladder system's permissions.
However despite this the use of your rules system is far too important to me to switch just for this.

**Comment by djxy** [comment]
I'm not sure to understand what you want. You want that can be on or off. Example: On is when the player is doing his job(staff) and off is when he is playing? When he is doing his job, he have access to some permissions that he doesn't have when he is playing?

**Comment by majix560** [comment]
No.
A moderator only able to use the promotion for On and Off duty mod, but NOT the promotion for on and off duty admin.
I want per promotion permissions so I can do this.
At the moment I can only give permission for either all promotions, or none at all.
I want the ability to give permission for specific promotions, while denying permission for others.

**Comment by djxy** [comment]
Currently with a permission, you can add and remove a permission. When you add it, you have the possibility to deny it. So, I"m not sure to understand what you really want.

Currently, you could create a promotion `Admin` that remove all the permissions of the promotion `Moderator` when you applied on a player.

The thing that I'm really not sure is the On and Off duty. I don't understand what you mean.

**Comment by majix560** [comment]
No.
A moderator only able to use the promotion for On and Off duty mod, but NOT the promotion for on and off duty admin.
I want per promotion permissions so I can do this.
At the moment I can only give permission for either all promotions, or none at all.
I want the ability to give permission for specific promotions, while denying permission for others.

**Comment by djxy** [comment]
Not sure to understand permissions per promotion. Currently, when you create à promotion you can set permissions only for this promotion.

**Comment by majix560** [comment]
There's only one permission to apply promotions, and it allows people to apply any/all promotions.
permissionmanager.commands.promotions.promote
I want something like this
permissionmanager.commands.promotions.promote.Mod-On
That only allows people to apply the Mod-On promotion.

**Comment by djxy** [comment]
You want à permission like this `permissionmanager.commands.promotions.promote.<name of the promotion>` that can only apply the promotion specified?

**Comment by majix560** [comment]
correct

**Comment by djxy** [comment]
Okay, no problem I can add this.

**Comment by majix560** [comment]
hopefully for the 1.10.2 version...
Harvest Festival mod is only for 1.10.2 and I haven't yet found a mod to add that makes me comfortable removing Harvest Festival yet.

**Comment by djxy** [comment]
The features I add always target the Sponge API that I support and 1.10.2 is supported by Sponge API 5.

**Comment by majix560** [comment]
@djxy I don't suppose there's an eta as to when the functionality I requested will be in?

**Comment by djxy** [comment]
I don't know when, but probably in the second week of January. I won't be able to release it before.

**Comment by djxy** [comment]
@GazbonicAcid It is added and it will be released in the v3 of PM.
