### ISSUE TITLE
[Feature Request] Database Support

### ISSUE THREAD

**Issue by hugeblank** [djxy/PermissionManager#28]
I swear I thought Permission Manager had database support but apparently I was wrong! I have 3 servers that I want to run off of the same database, rather than logging in, changing the permission, logging out, and repeating that 2 more times.

**Comment by djxy** [comment]
Yes, it is something I would like to add.

**Comment by djxy** [comment]
@hugeblank MySQL will be supported.

**Comment by hugeblank** [comment]
*is excited*

**Comment by djxy** [comment]
Added in the new version.
