### ISSUE TITLE
Context issue keeping groups from being listed in Nucleus /list.

### ISSUE THREAD

**Issue by ProsperCraft** [djxy/PermissionManager#29]
https://github.com/NucleusPowered/Nucleus/issues/542#event-907505156

**Comment by djxy** [comment]
I understand the problem. I will check that in à week. I dont have access to my computer currently.

**Comment by dualspiral** [comment]
Is there any movement on this? I've got quite a few users now asking about it.

**Comment by djxy** [comment]
Yes, I'm currently working on the new version of PM and this is fix. I will fix it for the current version probably today. I'm currently waiting the results of the tests of Blood for the bug with GP, after that I will work on it.

**Comment by djxy** [comment]
@ProsperCraft @dualspiral  It is fixed and it will be released in the v3 of PM.
