### ISSUE TITLE
Group inheriting the default group doesn't save over restart

### ISSUE THREAD

**Issue by turtledude01** [djxy/PermissionManager#34]
First off, my groups go as follows Member(default) ->trusted->staff
Every time the server restarts, Trusted loses the group Member.  I'm not sure why this is but It is a bit annoying.  I have tried saving all groups and nothing has worked.  The file for the Trusted group does have Member as a group in itself, which makes it strange that Trusted does not get Member on reload.

**Comment by djxy** [comment]
Are you reloading the file after you edit it? If it still does IT, you should add the group Member to trusted with the command.

**Comment by turtledude01** [comment]
I have been saving the files, yes, and it also randomly adds a new "default-XXXX" group  after a reboot

**Comment by djxy** [comment]
It add this group, because there is no default group.
