### ISSUE TITLE
How do I add permissions to users to access chests, doors etc?

### ISSUE THREAD

**Issue by Hund** [djxy/PermissionManager#40]
How do I add permissions to users to access chests, doors etc? I'm running a private server and I want everyone to have access to every inventory, doors etc. How do I do that?

**Comment by djxy** [comment]
It depends the plugins you are using. Also, you should join the discord https://discord.gg/GqSwu52.

**Comment by Hund** [comment]
I use PM with Nucleus. :) I don't use Discord.

**Comment by djxy** [comment]
Use the debug mode and check the permission when you try to open a door or something like that. You should be able to do it.

**Comment by Hund** [comment]
This is solved. Apparently `spawn-protection` (in server.properties) is a thing. It's funny how I never found out about this earlier. :)
