### ISSUE TITLE
[3.0.0] Subject issue with Nucleus's chat name hover?

### ISSUE THREAD

**Issue by leelawd** [djxy/PermissionManager#41]
![image](https://cloud.githubusercontent.com/assets/3026728/23638315/d88b00f0-02d8-11e7-89ed-4be998400426.png)

After testing out the new 3.0.0 update i came across this.

**Comment by djxy** [comment]
Which functionality of Nucleus is it? I will test it.

**Comment by djxy** [comment]
Thanks, I will check that.

**Comment by leelawd** [comment]
Sorry, after you suggested the config, having a quick look through i found that this is actually a config generation issue with nucleus. defaulting {{subject}} instead of {{player}} which is what it is meant to be.
