### ISSUE TITLE
Getting This is not a command

### ISSUE THREAD

**Issue by Levvy055** [djxy/PermissionManager#42]
Whenever I try to run command from console I got the mentioned error.

**Comment by djxy** [comment]
Can I have the command you are doing and the version of sponge you are using? Also, are you using the v3 of PermissionManager?

**Comment by Levvy055** [comment]
PermissionManager-2.6.0-API-5.X-6.X.jar
spongeforge-1.10.2-2221-5.2.0-BETA-2211.jar

Any commands like /pm groups, /pm users from https://github.com/djxy/PermissionManager/wiki/Eng-%E2%80%94-Commands

**Comment by djxy** [comment]
Do you have an error in logs when the server start?

**Comment by Levvy055** [comment]
Nope. Nothing in logs. I am also using nucleus plugin. Haven't checked yet without it because there are people playing now. Will check later if this is incompatibility with it.

**Comment by djxy** [comment]
If you can, you should switch to the new version of PermissionManager. You version should be compatible with Nucleus.

**Comment by ryan1246** [comment]
I'm getting this problem too, but i'm running 3.0.1. I go and type /pm in game and in console and I get Unknown command.

**Comment by djxy** [comment]
I only tested with Sponge API 5.1. the other versions 5.x should work, but I can't guarantee it. Which version of Sponge API do you have?

**Comment by ryan1246** [comment]
This is what I get from the console:
[13:57:54] [Server thread/INFO] [nucleus]: Server ran the command: /sponge version
[13:57:54] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
    SpongeForge: 1.10.2-2221-5.2.0-BETA-2223
    Minecraft Forge: 12.18.3.2254
> pm
[13:58:31] [Server thread/INFO] [nucleus]: Server ran the command: /pm
[13:58:31] [Server thread/INFO]: No such command

**Comment by ryan1246** [comment]
I'll try sponge API 5.1 and see if it helps

**Comment by ryan1246** [comment]
I dropped back down to 5.1 but it doesn't help.
> sponge version
[14:08:25] [Server thread/INFO] [nucleus]: Server ran the command: /sponge version
[14:08:25] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-cf4dfb1
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2210
    Minecraft Forge: 12.18.3.2254
> pm
[14:08:30] [Server thread/INFO] [nucleus]: Server ran the command: /pm
[14:08:30] [Server thread/INFO]: No such command

**Comment by djxy** [comment]
Try a command of the wiki. This one doesn't exist in v3

**Comment by ryan1246** [comment]
Ah thanks, it registered /pm group Visitor default

**Comment by ryan1246** [comment]
Also just a quick question, what is the equivalent command for /pm menu in version 3.0.1? I cant find it in the wiki.

**Comment by djxy** [comment]
The menu has not been updated yet.

**Comment by ryan1246** [comment]
Ok nvm, thanks
