### ISSUE TITLE
HOW TO SET A GROUP CANT PLACE DESTORY AND INTERACT WITH BLOCKS？

### ISSUE THREAD

**Issue by TehporP** [djxy/PermissionManager#48]
WIKI DIDNT TALK ABOUT IT   HOW CAN I DO DAT?

**Comment by djxy** [comment]
To control who can break and place a block, you have to use a plugin. PermissionManager only manage the permissions, but RedProtect and GriefPrevention can control these actions. You have to use a plugin like these ones and then check the permissions that control these actions.
