### ISSUE TITLE
Crash when using EssentialCmds with PermissionManager

### ISSUE THREAD

**Issue by knackrack615** [djxy/PermissionManager#6]
Whenever i use those 2 together the server crashes

According to the devs over @EssentialCmds this is a problem with PermissionManager ([issue](https://github.com/hsyyid/EssentialCmds/issues/134))

(Theres also a forestry error but i don't really see how forestry can interfere with EssentialCmds)

[Error Log](https://scrgrb.xyz/t/2016-08-09_14-07-02.txt)
[Full Server Log](https://scrgrb.xyz/t/2016-08-09_14-06-10.txt)

**Comment by djxy** [comment]
Which version of Sponge are you using?

**Comment by knackrack615** [comment]
spongeforge-1.10.2-2044-5.0.0-BETA-1660

**Comment by djxy** [comment]
You are using Sponge API 5.0. Currently, PermissionManager  doesn't works with this version. I'm currently working on a new version of PermissionManager to works with Sponge API 5.0

**Comment by knackrack615** [comment]
Alright cool, do you have any test builds i can try? i can help you beta test a bit if you want :)

**Comment by djxy** [comment]
Not yet, I will post the beta build on Sponge.
